### ISSUE TITLE
de ce e publica metoda asta? nu e un behavior cerut in tema

### ISSUE THREAD

**Issue by stefanbulzan** [TocutPatrick/beta-curs12-homework#3]
https://github.com/TocutPatrick/beta-curs12-homework/blob/f648816756d03326cee68413ebb376c1322e4849/src/beta/curs12/homework/ex3/IntTools.java#L13

**Comment by TocutPatrick** [comment]
Aici am făcut un behavior care sa îmi facă returneze lista cu fiecare cifra din număr si pe care am apelat-o din celalalte behavior-uri

**Comment by stefanbulzan** [comment]
dar doar in interiorul clasei, deci trebuia sa fie privata. Putem face oricate alte metode in plus, dar le pune private, pentru ca nu fac parte din behaviourul exterior al obiectului. Nu s-a cerut, nu e nevoie sa fie expus in exterior
