### ISSUE TITLE
arata may bine daca-i zici dayofWeek sau weekDay sau day

### ISSUE THREAD

**Issue by stefanbulzan** [TocutPatrick/beta-curs12-homework#5]
https://github.com/TocutPatrick/beta-curs12-homework/blob/f648816756d03326cee68413ebb376c1322e4849/src/beta/curs12/homework/extra1/DaySchedule.java#L7

**Comment by TocutPatrick** [comment]
Mi-am dat seama ca mi o fost destul de complicat de folosit. Nu știu de ce nu l am schimbat
