### ISSUE TITLE
reference escape

### ISSUE THREAD

**Issue by stefanbulzan** [TocutPatrick/beta-curs12-homework#7]
https://github.com/TocutPatrick/beta-curs12-homework/blob/f648816756d03326cee68413ebb376c1322e4849/src/beta/curs12/homework/extra1/DaySchedule.java#L20

**Comment by TocutPatrick** [comment]
Aici e suficient daca la inițializare am scris final?
private final List<String> activities = new ArrayList<>();

**Comment by stefanbulzan** [comment]
nu, de fiecare data cand dai referinta ca return, trebuie sa faci o copie...         return activities;
 devine         return new ArrayList<>(activities);
